- README.md
Added some updates to the readme documentation.
> Some updates on the readme doc

- README.md
- games/minecraft/minecraft_simulator.cpp
- games/minecraft/minecraft_simulator.h
- games/simple_race/simple_race_simulator.cpp
- games/simple_race/simple_race_simulator.h
- games/xworld/confs/walls.json
- games/xworld/xworld_simulator.cpp
- games/xworld/xworld_simulator.h
- python/examples/test_minecraft_simulator.py
- python/examples/test_simple_race.py
- python/examples/test_xworld_simulator.py
- python/py_simulator.cpp
More details for creating games. TODO: write C++ test binaries similar to Python test files.
> Add instructions for creating games and test_simple_race

- examples/test_atari.cpp
- examples/test_simple_race.cpp
- examples/test_xworld.cpp
- games/arcade/arcade_simulator.cpp
- games/simple_race/simple_race_simulator.cpp
- games/xworld/xworld_simulator.cpp
- python/examples/test_simple_race.py
- python/py_simulator.cpp
- simulator.h
- tests/test_xworld_task.cpp
Different Gflags have different namespace.
> Gflags cmake

- confs/lang.json
- python/examples/test_xworld.py
Add an example for interactive language learning setting in XWorld2D.
> add example for interactive language learning environment

- games/xworld/xworld/xworld.cpp
- games/xworld/xworld/xworld.h
- games/xworld/xworld_simulator.cpp
- simulator.cpp
- simulator.h
robot can now know from the env whether its action takes effect
> add a action success flag

- README.md
- games/xworld/maps/xworld_env.py
- games/xworld/tasks/xworld_task.py
- games/xworld/xworld/xmap.cpp
- games/xworld/xworld_simulator.cpp
- python/context_free_grammar.py
- python/examples/test_xworld.py
- python/py_simulator.cpp
Also add flag ego_centric to xworld2d.
> more comments and copyright headers

- CMakeLists.txt
- games/xworld3d/x3scene.h
- games/xworld3d/xworld3d_simulator.cpp
- simulator_entity.h
the change is for our robot repo
> fix simulator build

- games/xworld/maps/XWorldNav.py
- games/xworld/maps/xworld_env.py
- games/xworld/tasks/xworld_task.py
- games/xworld/xworld/xworld.cpp
- games/xworld/xworld_simulator.cpp
- games/xworld3d/maps/XWorld3DNav.py
- games/xworld3d/maps/xworld3d_env.py
- games/xworld3d/tasks/xworld3d_task.py
- games/xworld3d/xworld3d_simulator.cpp
- python/py_init.cpp
- teacher.cpp
Now the teacher increases the difficulty level by observing the agent's performance. If the success rate is higher than the predefined threshold, the teacher sets the environment for the next level.
> add curriculum learning based on agent's performance

- README.md
- confs/walls3d.json
- games/xworld3d/maps/xworld3d_env.py
- python/examples/test_xworld3d.py
- python/py_simulator.cpp
Just in case that other team members will use this preliminary version of xworld3d
> add python interface and example for xworld3d

- games/xworld3d/maps/XWorld3DNav.py
- games/xworld3d/maps/xworld3d_env.py
- games/xworld3d/tasks/XWorld3DNavTarget.py
- games/xworld3d/tasks/xworld3d_task.py
- games/xworld3d/xworld3d_simulator.cpp
- teaching_task.cpp
fix the bug of maze generation
> multi-goal on 7x7 maps with blocks 85%

- README.md
- games/simple_game/README.md
- games/simple_race/README.md
- games/xworld3d/README.md
Some updates to the README files with some typo fixes.
> readme file update

- games/xworld3d/README.md
Add detailed instructions on installing ffmpeg on Ubuntu14.04 with a few other minor updates to the text.
> Add some more detailed instructions on installing ffmpeg on Ubuntu14.04

- games/xworld3d/tasks/xworld3d_task.py
Now whenever the agent hits a goal, the game ends with a wrong_goal_reward
> change the reward for NavTargetSide

- examples/test_xworld_dialog.sh
- games/xworld/maps/XWorldDialogMap.py
- games/xworld/maps/xworld_env.py
- games/xworld/tasks/XWorldDialog.py
- python/examples/test_xworld.py
1) improved the se_property_function function in xworld_env.py to make it more flexible and easy to use
2) fixed a few bugs to make the dialog-based language learning setting work
> Improve set_property function in xworld_env.py with a few bug fixes

- games/xworld/maps/xworld_env.py
- games/xworld/tasks/XWorldDialog.py
Added additional check for handling the cases where the color property is not specified for some goals in properties.txt. Fixed a bug in XWorldDialog.
> handle the cases with unspecified color properties and fix a bug

- simulator.cpp
- simulator.h
- simulator_interface.cpp
This happens when the teacher changes the environment during teach stage.
> fix a bug that makes the perceived image mis-aligned with sentence.

- games/xworld/maps/XWorldDialogMap.py
- games/xworld/maps/XWorldLanguage.py
- games/xworld/maps/XWorldNavStaticObj.py
- games/xworld/maps/xworld_env.py
- games/xworld/tasks/XWorldLanDirectionToObject.py
- games/xworld/tasks/XWorldLanObjectToDirection.py
- python/py_util.py
*improved the function so that users do not need to delete and add back
entities in order to specify initial locations of entities.
> further improve 2d set_property function

- games/xworld/maps/XWorldDialogMap.py
- games/xworld/tasks/XWorldDialog.py
- games/xworld/xworld_simulator.cpp
- games/xworld/xworld_simulator.h
- python/examples/test_xworld.py
1) add image variation
2) add word level task
3) add sparse reward mode
> Improve the dialog environment

- games/xworld/maps/xworld_env.py
- games/xworld/xworld/xitem.cpp
- games/xworld/xworld/xitem.h
- games/xworld/xworld/xmap.cpp
- games/xworld/xworld/xmap.h
- games/xworld/xworld_simulator.cpp
- games/xworld/xworld_simulator.h
- games/xworld3d/xworld3d_simulator.cpp
The five navigation tasks are to be migrated from xworld3d to xworld2d
> add fog regions for xworld2d; enable keyboard control

- games/xworld3d/maps/xworld3d_env.py
fixed a bug related to setting entity id
> fix entity id related bug in 3d

- README.md
Add ACL paper to the readme file and also fixed a broken link for the ICLR paper.
> add ACL paper to readme
